name: DataSchema Code Convention

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint_sql_schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sqlfluff
        run: pip install sqlfluff

      - name: Lint DataSchema.sql with sqlfluff (MySQL dialect)
        run: sqlfluff lint DataSchema.sql --dialect mysql
